corelm: valle
corelm_conf:
    share_emb: false
    att_unit: 512
    head: 8
    ar_layer: 12
    nar_layer: 12

# Dataloader
batch_type: numel
batch_bins: 12000
accum_grad: 1
grad_clip: 5
max_epoch: 50
num_workers: 4
drop_last_iter: true
log_interval: 500

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.0002
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 7000

best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 5
nbest_averaging_interval: 5

# Global settings
use_amp: true
use_tf32: false
use_fsdp: false
encoder_decoder_format: false
codec_token_per_frame: 8
codec_token_in_use: 8
speaker_prompt_length: 225 # 75fps, a.k.a., 3s
