# Trained with Tesla 8xA100-SXM4-40GB. It takes about ? hours.
# #Params: 1.15B
corelm: multiscale
corelm_conf:
    share_emb: false
    # global transformer
    g_att_unit: 2048
    g_head: 32
    g_layer: 22
    # local transformer
    l_att_unit: 384
    l_head: 6
    l_layer: 6
    first_layer_weight: 1.0

# Dataloader
batch_type: numel
num_att_plot: 0     # master process cannot forward along
batch_bins: 30000
accum_grad: 1
grad_clip: 5
max_epoch: 100
num_workers: 4
drop_last_iter: true
log_interval: 500

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.0002
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 20000

best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 5
nbest_averaging_interval: 5


# Global settings
use_amp: true
use_tf32: false
use_fsdp: true
encoder_decoder_format: false
codec_token_per_frame: 8 # encodec
codec_token_in_use: 8
speaker_prompt_length: 150 # 75fps, a.k.a., 3s
