use_deepspeed: true
deepspeed_config: conf/deepspeed_ddp_tts.json

corelm: ar_delay
corelm_conf:
    share_emb: false
    qk_norm: true
    att_unit: 1024
    head: 16
    layer: 24

# Dataloader
batch_type: numel
batch_bins: 32000
num_iters_per_epoch: 10000
max_epoch: 40
num_workers: 8
drop_last_iter: true
log_interval: 1000
codec_token_per_frame: 8 # encodec
codec_token_in_use: 8
speaker_prompt_length: 500 # 50fps, a.k.a., 10s
